# Quick aliases for common commands
alias 1ping='ping 1.1.1.1'
alias c='cargo'
alias cdt='cd $(mktemp -d)'
alias d='docker'
alias dc='docker-compose'
alias e='$EDITOR'
alias g='git'
alias h='helm'
alias ipy='ipython'
alias ipa='ip -c -br a'
alias jc='curl -H "Content-Type: application/json"'
alias k='kubectl'
alias kn='kubens'
alias kc='kubectx'
alias l='locate -i'
alias ll='ls -lah --color=always'
alias lp='locate -i -A "$(pwd)"'
alias n='echo -e "\a" && notify-send -a "Terminal" Notification!'
alias p='podman'
alias pc='podman-compose'
alias py='python'
alias v='nvim'
alias sv='sudoedit'
alias tf='terraform'

# Nicer output
alias man='LC_ALL=C LANG=C man'
alias pgrep='pgrep -af'
alias ssh='TERM=xterm-256color ssh'
alias diff='diff --color=always'
alias now='date +"%Y.%m.%d-%H.%M.%S"'
# By https://unix.stackexchange.com/questions/25327/watch-command-alias-expansion
alias watch='watch -c '

# Useful aliases
alias docker_rm='docker rm $(docker ps --no-trunc -aqf status=exited)'
alias docker_rmi='docker rmi $(docker images --no-trunc -qf dangling=true)'
alias open='xdg-open'
alias passgen='gpg --armor --gen-random 2 '
alias weather='curl wttr.in'
alias webserver='python3 -m http.server'

# Hipster tools
alias cat='bat -p --paging=never'
alias diff='colordiff -ub'
alias grep='rg'
alias less='bat -p'
alias ll='lsd -Fal'
alias ls='lsd -F'
alias find='fd'
