#!/bin/sh

sxhkd &

bspc monitor -d term web mail vm music

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          22
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "#666666"
bspc config active_border_color "#666666"
bspc config focused_border_color "#cccccc"
bspc config presel_feedback_color "#888888"

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'

~/.config/bspwm/autostart.sh
