#!/bin/sh
# .todir syntax: "+" high, "#" medium, "-" low priority and "//" comment.
# For syntax highlighting take a look at .vim/syntax/todir.vim

LOW='\x1b[32m'		#Green
MID='\x1b[36m'		#Cyan
HIGH='\x1b[33m'		#Yellow

while getopts "chrs" opt; do
	case "$opt" in
		c)
			grep -cs "^\s*+\|^\s*#\|^\s*-" .todir
			exit
			;;
		h)
			echo -e "ToDir v0.4"
			echo -e "Usage ${0}: [-c] [-h] [-r] [path]\n"
			echo -e "A directory based todo list manager. Create a .todir file and add tasks!\n"
			echo -e "\tpath\tPath of directory which contains .todir, default to current directory"
			echo -e "\t-c\tReturns number of tasks"
			echo -e "\t-h\tShows this message"
			echo -e "\t-r\tShows tasks of all subfolders, recursively"
			echo -e "\t-s\tSearch source code under path for tasks"
			exit
			;;
		r)
			find . -name .todir -exec echo "$0:" \; -exec $0 {} \; -exec echo "" \;
			;;
		s)
			data=`grep -r "FIXME\|TODO\|XXX" * | \
				awk -F ":" '/FIXME|TODO|XXX/ \
				{ printf "%s", $2; for(i=3;i<=NF;++i) printf "%s", $i; print ", at: " $1 }' | \
				sed "s/.*TODO\s*/- /; \
				s/.*FIXME\s*/# /; \
				s/.*XXX\s*/+ /"`
			;;
		*)
			;;
	esac
done

shift $(($OPTIND - 1))
tpath=$(echo ${1} | sed "s/.todir$//")

if [ -z "$tpath" ]; then
	tpath="."
fi

if [ -z "$data" ]; then
	data="$(grep -v '^//' $tpath/.todir 2>/dev/null)"
else
	data="$data\n$(grep -v '^//' $tpath/.todir 2>/dev/null)"
fi

echo -e "$data" | sed "s/^\s*+.*/a${HIGH}&/; \
	s/^\s*#.*/b${MID}&/; \
	s/^\s*-.*/c${LOW}&/" | \
	sort -s -k 1.1,1.1 | sed "s/^[abc]//"
