name: Build and Release NixOS ISO

on:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up some disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up cache for /nix/store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix

      - name: Build the ISO image
        run: nix build ./nix#iso

      - name: Generate tag name
        id: tag
        run: echo "name=$(ls result/iso/ | sed -E 's/.*\.([[:alnum:]]+)-.*/iso-\1/')" >> $GITHUB_OUTPUT

      - uses: oras-project/setup-oras@v1
      - run: |
          cd result/iso
          oras login ghcr.io -u github -p ${{ secrets.GITHUB_TOKEN }}
          oras push ghcr.io/${{ github.repository }}/nixos-iso:${{ steps.tag.outputs.name }},latest *.iso ../../README.md:text/markdown
