name: Update NixOS

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up some disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Set up cache for /nix/store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix

      - name: Update the flake
        run: nix flake update --flake .

      - name: Build the ISO image
        # If there are dirty files, build the iso
        run: git diff-files --quiet || nix build .#iso

      - name: Commit and push changes
        # If there are no dirty files, don't commit anything
        run: |
          git diff-files --quiet && exit 0
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add flake.lock
          git commit -m "Update flake.lock"
          git push
